### ISSUE TITLE
Cleanup TODO

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/acrobotics#5]
Some cleaning before I start adding new things:

- [ ] Move geometry and plotting utils to [acrolib](https://github.com/JeroenDM/acrolib)
- [ ] Remove old `ShapeSoup` name in favor of `Scene`.
- [ ] Move IRL parsing out in favor of [rotasp](https://gitlab.kuleuven.be/ACRO/rotasp)
- [ ] Check usage of `check_rxyz_input` and possibly also move to `acrolib.geometry`.
